import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const [activity, setActivity] = useState("");
    const [todos, setTodos] = useState([]);

    useEffect(() => {
        FetchTodos();
    }, []);

    async function FetchTodos() {
        try {
            const response = await fetch("/api/listTodos");
            const data = await response.json();
            console.log(data);
            setTodos(data);
        } catch (error) {
            console.log("error fetching todos", error);
        }
    }

    async function AddTodo(event) {
        // event.preventDefault();
        // if (activity !== "") {
        //     try {
        //         const todo = {
        //             id: Date.now(),
        //             title: activity,
        //             completed: false,
        //         };
        //         const newTodo = await API.graphql(
        //             graphqlOperation(createTodo, { input: todo }),
        //         );
        //         setTodos([...todos, newTodo.data.createTodo]);
        //     } catch (error) {
        //         console.log("error creating todo:", error);
        //     }
        //     setActivity("");
        // }
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <button onClick={FetchTodos}>fetch button</button>
                <div className={styles.grid}>
                    <div
                        href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2 className={inter.className}>Todo App</h2>
                        <p className={inter.className}>
                            Sorry for broken layout 😬
                        </p>
                        <p className={inter.className}>
                            The only working function is fetch function. it
                            triggered at first render and you can also hit fetch
                            button to refetch and see the result in console.
                        </p>
                        <form onSubmit={AddTodo}>
                            <input
                                type="text"
                                placeholder="what to do?"
                                value={activity}
                                onChange={(e) => setActivity(e.target.value)}
                                disabled
                            />
                            <button disabled>Add Task</button>
                        </form>
                    </div>

                    <div
                        href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2 className={inter.className}>What Todo</h2>
                        <ul className={inter.className}>
                            {todos.map((todo) => (
                                <li key={todo.id}>{todo.title}</li>
                            ))}
                        </ul>
                    </div>
                </div>
            </main>
        </>
    );
}

export async function getServerSideProps(context) {
    return {
        props: {}, // will be passed to the page component as props
    };
}
